//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace video_stream_researcher.Resources {
    using System;
    using System.Resources;
    using System.Globalization;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("video_stream_researcher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        internal static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开始处理.
        /// </summary>
        internal static string ButtonStartProcessing {
            get {
                return ResourceManager.GetString("ButtonStartProcessing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 预览编辑.
        /// </summary>
        internal static string CheckBoxPreviewEdit {
            get {
                return ResourceManager.GetString("CheckBoxPreviewEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 保留原文件.
        /// </summary>
        internal static string CheckBoxKeepOriginal {
            get {
                return ResourceManager.GetString("CheckBoxKeepOriginal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 下载后自动预览.
        /// </summary>
        internal static string CheckBoxAutoPreview {
            get {
                return ResourceManager.GetString("CheckBoxAutoPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 当前速度: 0 MB/s.
        /// </summary>
        internal static string InitialSpeedText {
            get {
                return ResourceManager.GetString("InitialSpeedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语言：.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 视频链接：.
        /// </summary>
        internal static string LabelVideoUrl {
            get {
                return ResourceManager.GetString("LabelVideoUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 保存路径：.
        /// </summary>
        internal static string LabelSavePath {
            get {
                return ResourceManager.GetString("LabelSavePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 提示：登录B站账号可以获取高清视频。输入 &apos;bili&apos; 开始登录流程。.
        /// </summary>
        internal static string LoginPrompt {
            get {
                return ResourceManager.GetString("LoginPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 下载全部.
        /// </summary>
        internal static string RadioButtonAll {
            get {
                return ResourceManager.GetString("RadioButtonAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 不合并.
        /// </summary>
        internal static string RadioButtonNoMerge {
            get {
                return ResourceManager.GetString("RadioButtonNoMerge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 仅音频.
        /// </summary>
        internal static string RadioButtonAudioOnly {
            get {
                return ResourceManager.GetString("RadioButtonAudioOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 仅视频.
        /// </summary>
        internal static string RadioButtonVideoOnly {
            get {
                return ResourceManager.GetString("RadioButtonVideoOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 就绪.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 正在解析....
        /// </summary>
        internal static string StatusParsing {
            get {
                return ResourceManager.GetString("StatusParsing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 正在下载....
        /// </summary>
        internal static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 分段数：.
        /// </summary>
        internal static string TextBlockSegmentCount {
            get {
                return ResourceManager.GetString("TextBlockSegmentCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to （仅HLS）.
        /// </summary>
        internal static string TextBlockHlsOnly {
            get {
                return ResourceManager.GetString("TextBlockHlsOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 取消下载.
        /// </summary>
        internal static string TooltipCancelDownload {
            get {
                return ResourceManager.GetString("TooltipCancelDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 切换主题.
        /// </summary>
        internal static string TooltipToggleTheme {
            get {
                return ResourceManager.GetString("TooltipToggleTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 视频流解析工具.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已复制到剪贴板.
        /// </summary>
        internal static string MessageCopySuccess {
            get {
                return ResourceManager.GetString("MessageCopySuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 下载失败.
        /// </summary>
        internal static string MessageDownloadError {
            get {
                return ResourceManager.GetString("MessageDownloadError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 解析失败.
        /// </summary>
        internal static string MessageParseError {
            get {
                return ResourceManager.GetString("MessageParseError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请输入视频链接.
        /// </summary>
        internal static string MessageUrlEmpty {
            get {
                return ResourceManager.GetString("MessageUrlEmpty", resourceCulture);
            }
        }
    }
}
